const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Quote = sequelize.define('Quote', {
    id: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey: true
    },
    quoteId: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true
    },
    pickupCountry: {
        type: DataTypes.STRING,
        allowNull: false
    },
    pickupCity: {
        type: DataTypes.STRING,
        allowNull: false
    },
    pickupZipCode: {
        type: DataTypes.STRING,
        allowNull: false
    },
    deliveryCountry: {
        type: DataTypes.STRING,
        allowNull: false
    },
    deliveryCity: {
        type: DataTypes.STRING,
        allowNull: true
    },
    deliveryZipCode: {
        type: DataTypes.STRING,
        allowNull: true
    },
    weight: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: false
    },
    packageType: {
        type: DataTypes.STRING,
        defaultValue: 'PARCELS'
    },
    serviceName: {
        type: DataTypes.STRING,
        allowNull: false
    },
    serviceCode: {
        type: DataTypes.STRING,
        allowNull: true
    },
    totalPrice: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: false
    },
    currency: {
        type: DataTypes.STRING,
        defaultValue: 'CHF'
    },
    etaMin: {
        type: DataTypes.INTEGER,
        allowNull: true
    },
    etaMax: {
        type: DataTypes.INTEGER,
        allowNull: true
    },
    status: {
        type: DataTypes.STRING,
        defaultValue: 'Active'
    },
    adminId: {
        type: DataTypes.UUID,
        allowNull: true // If generated by an admin
    },
    customerId: {
        type: DataTypes.UUID,
        allowNull: true // If generated by a customer
    }
}, {
    timestamps: true,
    tableName: 'quotes'
});

module.exports = Quote;
