export const countries = [
    { code: 'AF', name: 'AFGHANISTAN' },
    { code: 'AL', name: 'ALBANIA' },
    { code: 'DZ', name: 'ALGERIA' },
    { code: 'AD', name: 'ANDORRA' },
    { code: 'AO', name: 'ANGOLA' },
    { code: 'AR', name: 'ARGENTINA' },
    { code: 'AM', name: 'ARMENIA' },
    { code: 'AU', name: 'AUSTRALIA' },
    { code: 'AT', name: 'AUSTRIA' },
    { code: 'AZ', name: 'AZERBAIJAN' },
    { code: 'BH', name: 'BAHRAIN' },
    { code: 'BD', name: 'BANGLADESH' },
    { code: 'BE', name: 'BELGIUM' },
    { code: 'BR', name: 'BRAZIL' },
    { code: 'BG', name: 'BULGARIA' },
    { code: 'CA', name: 'CANADA' },
    { code: 'CN', name: 'CHINA' },
    { code: 'HR', name: 'CROATIA' },
    { code: 'CY', name: 'CYPRUS' },
    { code: 'CZ', name: 'CZECH REPUBLIC' },
    { code: 'DK', name: 'DENMARK' },
    { code: 'EG', name: 'EGYPT' },
    { code: 'EE', name: 'ESTONIA' },
    { code: 'FI', name: 'FINLAND' },
    { code: 'FR', name: 'FRANCE' },
    { code: 'GE', name: 'GEORGIA' },
    { code: 'DE', name: 'GERMANY' },
    { code: 'GR', name: 'GREECE' },
    { code: 'HK', name: 'HONG KONG' },
    { code: 'HU', name: 'HUNGARY' },
    { code: 'IS', name: 'ICELAND' },
    { code: 'IN', name: 'INDIA' },
    { code: 'ID', name: 'INDONESIA' },
    { code: 'IE', name: 'IRELAND' },
    { code: 'IL', name: 'ISRAEL' },
    { code: 'IT', name: 'ITALY' },
    { code: 'JP', name: 'JAPAN' },
    { code: 'JO', name: 'JORDAN' },
    { code: 'KZ', name: 'KAZAKHSTAN' },
    { code: 'KW', name: 'KUWAIT' },
    { code: 'LV', name: 'LATVIA' },
    { code: 'LB', name: 'LEBANON' },
    { code: 'LI', name: 'LIECHTENSTEIN' },
    { code: 'LT', name: 'LITHUANIA' },
    { code: 'LU', name: 'LUXEMBOURG' },
    { code: 'MY', name: 'MALAYSIA' },
    { code: 'MT', name: 'MALTA' },
    { code: 'MX', name: 'MEXICO' },
    { code: 'MC', name: 'MONACO' },
    { code: 'MA', name: 'MOROCCO' },
    { code: 'NL', name: 'NETHERLANDS' },
    { code: 'NZ', name: 'NEW ZEALAND' },
    { code: 'NO', name: 'NORWAY' },
    { code: 'OM', name: 'OMAN' },
    { code: 'PK', name: 'PAKISTAN' },
    { code: 'PH', name: 'PHILIPPINES' },
    { code: 'PL', name: 'POLAND' },
    { code: 'PT', name: 'PORTUGAL' },
    { code: 'QA', name: 'QATAR' },
    { code: 'RO', name: 'ROMANIA' },
    { code: 'SA', name: 'SAUDI ARABIA' },
    { code: 'SG', name: 'SINGAPORE' },
    { code: 'SK', name: 'SLOVAKIA' },
    { code: 'SI', name: 'SLOVENIA' },
    { code: 'ZA', name: 'SOUTH AFRICA' },
    { code: 'KR', name: 'SOUTH KOREA' },
    { code: 'ES', name: 'SPAIN' },
    { code: 'SE', name: 'SWEDEN' },
    { code: 'CH', name: 'SWITZERLAND' },
    { code: 'TW', name: 'TAIWAN' },
    { code: 'TH', name: 'THAILAND' },
    { code: 'TN', name: 'TUNISIA' },
    { code: 'TR', name: 'TURKEY' },
    { code: 'UA', name: 'UKRAINE' },
    { code: 'AE', name: 'UNITED ARAB EMIRATES' },
    { code: 'GB', name: 'UNITED KINGDOM' },
    { code: 'US', name: 'UNITED STATES' },
    { code: 'VN', name: 'VIETNAM' }
];
